### ISSUE TITLE
Compatibility problem after redis-rb 4.2.0

### ISSUE THREAD

**Issue by Youngv** [buyco/redis-stream-wrapper#8]
https://github.com/redis/redis-rb/blob/5dd7df9310b1bac97b4ae0385faf7ba6c0fee1d2/CHANGELOG.md#420
> Convert commands to accept keyword arguments rather than option hashes. This both help catching typos, and reduce needless allocations.

```ruby
redis = Redis.new
wrapper.create_group("group", "stream") rescue nil
wrapper.listen("group", "consumer", { 'stream' => '$' }) do |message|
  puts message
end
```

```shell
[dry-struct] Dry::Struct::Value is deprecated and will be removed in the next major version
lib/stream_listen.rb:2:in `<main>'
/usr/local/rvm/gems/ruby-3.0.2/gems/redis-4.4.0/lib/redis.rb:3213:in `xreadgroup': wrong number of arguments (given 5, expected 4) (ArgumentError)
```

**Comment by defgenx** [comment]
@Youngv thanks for openning an issue and sorry for the delay.

Can you please submit a PR to fix this issue ? I saw you made a fix on your side :)

**Comment by defgenx** [comment]
Resolved and PR merged.
